baseurl = "/"
languageCode = "pt-pt"
title = "Francisco Ribeiro"
theme = "hugo-theme-casper"
# disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Francisco Ribeiro"
  authorlocation = "Guarda, Portugal"
  authorwebsite = "https://www.franciscoribeiro.net"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "fmmribeiro"
  twitterName = "fmmribeiro"
  # facebookName = "fmmribeiro"
  # linkedinName = "fmmribeiro"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "fmmribeiro"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    name = "getting started"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"
    weight = -100
